"""Add multimodal columns to ChatTurn

Revision ID: 39e603e39a9b
Revises: d3ef84e2a5cf
Create Date: 2026-03-23 21:55:55.883711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e603e39a9b'
down_revision: Union[str, Sequence[str], None] = 'd3ef84e2a5cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_turns', sa.Column('message_type', sa.String(length=50), nullable=False))
    op.add_column('chat_turns', sa.Column('media_url', sa.Text(), nullable=True))
    op.add_column('chat_turns', sa.Column('media_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_turns', 'media_summary')
    op.drop_column('chat_turns', 'media_url')
    op.drop_column('chat_turns', 'message_type')
    # ### end Alembic commands ###
