"""Initial chat_turns table

Revision ID: 8c1684a4ff0e
Revises: 
Create Date: 2026-03-06 05:28:29.960420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1684a4ff0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('user_message_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent', 'chat_turns', ['agent_id'], unique=False)
    op.create_index('ix_agent_sender', 'chat_turns', ['agent_id', 'sender_id'], unique=False)
    op.create_index('ix_sender', 'chat_turns', ['sender_id'], unique=False)
    op.create_index('ix_timestamp', 'chat_turns', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
