"""add platform and composite index

Revision ID: d3ef84e2a5cf
Revises: 8c1684a4ff0e
Create Date: 2026-03-08 04:03:17.077422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ef84e2a5cf'
down_revision: Union[str, Sequence[str], None] = '8c1684a4ff0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_turns', sa.Column('platform', sa.String(length=50), server_default='whatsapp', nullable=False))
    op.drop_index(op.f('ix_agent'), table_name='chat_turns')
    op.drop_index(op.f('ix_agent_sender'), table_name='chat_turns')
    op.drop_index(op.f('ix_sender'), table_name='chat_turns')
    op.drop_index(op.f('ix_timestamp'), table_name='chat_turns')
    op.create_index('ix_chat_history_lookup', 'chat_turns', ['agent_id', 'platform', 'sender_id', sa.literal_column('timestamp DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_history_lookup', table_name='chat_turns')
    op.create_index(op.f('ix_timestamp'), 'chat_turns', ['timestamp'], unique=False)
    op.create_index(op.f('ix_sender'), 'chat_turns', ['sender_id'], unique=False)
    op.create_index(op.f('ix_agent_sender'), 'chat_turns', ['agent_id', 'sender_id'], unique=False)
    op.create_index(op.f('ix_agent'), 'chat_turns', ['agent_id'], unique=False)
    op.drop_column('chat_turns', 'platform')
    # ### end Alembic commands ###
